"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_sort_sort_column import NetCordaCoreNodeServicesVaultSortSortColumn


class TestNetCordaCoreNodeServicesVaultSortSortColumn(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultSortSortColumn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultSortSortColumn(self):
        """Test NetCordaCoreNodeServicesVaultSortSortColumn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultSortSortColumn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
