"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_state_ref import NetCordaCoreContractsStateRef
from openapi_client.model.net_corda_core_identity_abstract_party import NetCordaCoreIdentityAbstractParty
from openapi_client.model.net_corda_core_node_services_vault_constraint_info import NetCordaCoreNodeServicesVaultConstraintInfo
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_soft_locking_condition import NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_time_condition import NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition
globals()['NetCordaCoreContractsStateRef'] = NetCordaCoreContractsStateRef
globals()['NetCordaCoreIdentityAbstractParty'] = NetCordaCoreIdentityAbstractParty
globals()['NetCordaCoreNodeServicesVaultConstraintInfo'] = NetCordaCoreNodeServicesVaultConstraintInfo
globals()['NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition'] = NetCordaCoreNodeServicesVaultQueryCriteriaSoftLockingCondition
globals()['NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition'] = NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_vault_query_criteria_all_of import NetCordaCoreNodeServicesVaultQueryCriteriaVaultQueryCriteriaAllOf


class TestNetCordaCoreNodeServicesVaultQueryCriteriaVaultQueryCriteriaAllOf(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultQueryCriteriaVaultQueryCriteriaAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultQueryCriteriaVaultQueryCriteriaAllOf(self):
        """Test NetCordaCoreNodeServicesVaultQueryCriteriaVaultQueryCriteriaAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultQueryCriteriaVaultQueryCriteriaAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
