"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_identity_abstract_party import NetCordaCoreIdentityAbstractParty
from openapi_client.model.net_corda_core_schemas_persistent_state_ref import NetCordaCoreSchemasPersistentStateRef
globals()['NetCordaCoreIdentityAbstractParty'] = NetCordaCoreIdentityAbstractParty
globals()['NetCordaCoreSchemasPersistentStateRef'] = NetCordaCoreSchemasPersistentStateRef
from openapi_client.model.net_corda_core_schemas_common_schema_v1_linear_state import NetCordaCoreSchemasCommonSchemaV1LinearState


class TestNetCordaCoreSchemasCommonSchemaV1LinearState(unittest.TestCase):
    """NetCordaCoreSchemasCommonSchemaV1LinearState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreSchemasCommonSchemaV1LinearState(self):
        """Test NetCordaCoreSchemasCommonSchemaV1LinearState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreSchemasCommonSchemaV1LinearState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
