"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_and_composition import NetCordaCoreNodeServicesVaultQueryCriteriaAndComposition
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_common_query_criteria import NetCordaCoreNodeServicesVaultQueryCriteriaCommonQueryCriteria
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_fungible_asset_query_criteria import NetCordaCoreNodeServicesVaultQueryCriteriaFungibleAssetQueryCriteria
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_fungible_state_query_criteria import NetCordaCoreNodeServicesVaultQueryCriteriaFungibleStateQueryCriteria
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_linear_state_query_criteria import NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_or_composition import NetCordaCoreNodeServicesVaultQueryCriteriaOrComposition
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_vault_custom_query_criteria import NetCordaCoreNodeServicesVaultQueryCriteriaVaultCustomQueryCriteria
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_vault_query_criteria import NetCordaCoreNodeServicesVaultQueryCriteriaVaultQueryCriteria
globals()['NetCordaCoreNodeServicesVaultQueryCriteriaAndComposition'] = NetCordaCoreNodeServicesVaultQueryCriteriaAndComposition
globals()['NetCordaCoreNodeServicesVaultQueryCriteriaCommonQueryCriteria'] = NetCordaCoreNodeServicesVaultQueryCriteriaCommonQueryCriteria
globals()['NetCordaCoreNodeServicesVaultQueryCriteriaFungibleAssetQueryCriteria'] = NetCordaCoreNodeServicesVaultQueryCriteriaFungibleAssetQueryCriteria
globals()['NetCordaCoreNodeServicesVaultQueryCriteriaFungibleStateQueryCriteria'] = NetCordaCoreNodeServicesVaultQueryCriteriaFungibleStateQueryCriteria
globals()['NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria'] = NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteria
globals()['NetCordaCoreNodeServicesVaultQueryCriteriaOrComposition'] = NetCordaCoreNodeServicesVaultQueryCriteriaOrComposition
globals()['NetCordaCoreNodeServicesVaultQueryCriteriaVaultCustomQueryCriteria'] = NetCordaCoreNodeServicesVaultQueryCriteriaVaultCustomQueryCriteria
globals()['NetCordaCoreNodeServicesVaultQueryCriteriaVaultQueryCriteria'] = NetCordaCoreNodeServicesVaultQueryCriteriaVaultQueryCriteria
from openapi_client.model.net_corda_core_node_services_vault_query_criteria import NetCordaCoreNodeServicesVaultQueryCriteria


class TestNetCordaCoreNodeServicesVaultQueryCriteria(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultQueryCriteria unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultQueryCriteria(self):
        """Test NetCordaCoreNodeServicesVaultQueryCriteria"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultQueryCriteria()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
