"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_page_specification import NetCordaCoreNodeServicesVaultPageSpecification
from openapi_client.model.net_corda_core_node_services_vault_query_criteria import NetCordaCoreNodeServicesVaultQueryCriteria
from openapi_client.model.net_corda_core_node_services_vault_sort import NetCordaCoreNodeServicesVaultSort
globals()['NetCordaCoreNodeServicesVaultPageSpecification'] = NetCordaCoreNodeServicesVaultPageSpecification
globals()['NetCordaCoreNodeServicesVaultQueryCriteria'] = NetCordaCoreNodeServicesVaultQueryCriteria
globals()['NetCordaCoreNodeServicesVaultSort'] = NetCordaCoreNodeServicesVaultSort
from openapi_client.model.io_bluebank_braid_corda_services_vault_vault_query import IoBluebankBraidCordaServicesVaultVaultQuery


class TestIoBluebankBraidCordaServicesVaultVaultQuery(unittest.TestCase):
    """IoBluebankBraidCordaServicesVaultVaultQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoBluebankBraidCordaServicesVaultVaultQuery(self):
        """Test IoBluebankBraidCordaServicesVaultVaultQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IoBluebankBraidCordaServicesVaultVaultQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
