"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_scheduled_state_ref import NetCordaCoreContractsScheduledStateRef
globals()['NetCordaCoreContractsScheduledStateRef'] = NetCordaCoreContractsScheduledStateRef
from openapi_client.model.net_corda_core_context_invocation_origin_scheduled import NetCordaCoreContextInvocationOriginScheduled


class TestNetCordaCoreContextInvocationOriginScheduled(unittest.TestCase):
    """NetCordaCoreContextInvocationOriginScheduled unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreContextInvocationOriginScheduled(self):
        """Test NetCordaCoreContextInvocationOriginScheduled"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreContextInvocationOriginScheduled()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
