"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_sort_sort_column import NetCordaCoreNodeServicesVaultSortSortColumn
globals()['NetCordaCoreNodeServicesVaultSortSortColumn'] = NetCordaCoreNodeServicesVaultSortSortColumn
from openapi_client.model.net_corda_core_node_services_vault_sort import NetCordaCoreNodeServicesVaultSort


class TestNetCordaCoreNodeServicesVaultSort(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultSort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultSort(self):
        """Test NetCordaCoreNodeServicesVaultSort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultSort()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
