"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_state_ref import NetCordaCoreContractsStateRef
from openapi_client.model.net_corda_core_contracts_transaction_state_net_corda_core_contracts_contract_state import NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState
globals()['NetCordaCoreContractsStateRef'] = NetCordaCoreContractsStateRef
globals()['NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState'] = NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState
from openapi_client.model.net_corda_core_contracts_state_and_ref_net_corda_core_contracts_contract_state import NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState


class TestNetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState(unittest.TestCase):
    """NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState(self):
        """Test NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
