"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from io.generated.api.vault_api import VaultApi  # noqa: E501


class TestVaultApi(unittest.TestCase):
    """VaultApi unit test stubs"""

    def setUp(self):
        self.api = VaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_vault_vault_query(self):
        """Test case for vault_vault_query

        """
        pass

    def test_vault_vault_query_by(self):
        """Test case for vault_vault_query_by

        """
        pass


if __name__ == '__main__':
    unittest.main()
