"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_column_predicate_between_all_of import NetCordaCoreNodeServicesVaultColumnPredicateBetweenAllOf


class TestNetCordaCoreNodeServicesVaultColumnPredicateBetweenAllOf(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultColumnPredicateBetweenAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultColumnPredicateBetweenAllOf(self):
        """Test NetCordaCoreNodeServicesVaultColumnPredicateBetweenAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultColumnPredicateBetweenAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
