"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_identity_party import NetCordaCoreIdentityParty
from openapi_client.model.net_corda_core_utilities_network_host_and_port import NetCordaCoreUtilitiesNetworkHostAndPort
globals()['NetCordaCoreIdentityParty'] = NetCordaCoreIdentityParty
globals()['NetCordaCoreUtilitiesNetworkHostAndPort'] = NetCordaCoreUtilitiesNetworkHostAndPort
from openapi_client.model.io_bluebank_braid_corda_services_simple_node_info import IoBluebankBraidCordaServicesSimpleNodeInfo


class TestIoBluebankBraidCordaServicesSimpleNodeInfo(unittest.TestCase):
    """IoBluebankBraidCordaServicesSimpleNodeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoBluebankBraidCordaServicesSimpleNodeInfo(self):
        """Test IoBluebankBraidCordaServicesSimpleNodeInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IoBluebankBraidCordaServicesSimpleNodeInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
