"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_utilities_byte_sequence import NetCordaCoreUtilitiesByteSequence


class TestNetCordaCoreUtilitiesByteSequence(unittest.TestCase):
    """NetCordaCoreUtilitiesByteSequence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreUtilitiesByteSequence(self):
        """Test NetCordaCoreUtilitiesByteSequence"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreUtilitiesByteSequence()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
