"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_node_info import NetCordaCoreNodeNodeInfo
globals()['NetCordaCoreNodeNodeInfo'] = NetCordaCoreNodeNodeInfo
from openapi_client.model.net_corda_core_node_services_network_map_cache_map_change import NetCordaCoreNodeServicesNetworkMapCacheMapChange


class TestNetCordaCoreNodeServicesNetworkMapCacheMapChange(unittest.TestCase):
    """NetCordaCoreNodeServicesNetworkMapCacheMapChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesNetworkMapCacheMapChange(self):
        """Test NetCordaCoreNodeServicesNetworkMapCacheMapChange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesNetworkMapCacheMapChange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
