"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_unique_identifier import NetCordaCoreContractsUniqueIdentifier
globals()['NetCordaCoreContractsUniqueIdentifier'] = NetCordaCoreContractsUniqueIdentifier
from openapi_client.model.generated_flows_event_update_flow_event_update_flow_initiator_payload import GeneratedFlowsEventUpdateFlowEventUpdateFlowInitiatorPayload


class TestGeneratedFlowsEventUpdateFlowEventUpdateFlowInitiatorPayload(unittest.TestCase):
    """GeneratedFlowsEventUpdateFlowEventUpdateFlowInitiatorPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneratedFlowsEventUpdateFlowEventUpdateFlowInitiatorPayload(self):
        """Test GeneratedFlowsEventUpdateFlowEventUpdateFlowInitiatorPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeneratedFlowsEventUpdateFlowEventUpdateFlowInitiatorPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
