"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_column_predicate_instant import NetCordaCoreNodeServicesVaultColumnPredicateInstant
globals()['NetCordaCoreNodeServicesVaultColumnPredicateInstant'] = NetCordaCoreNodeServicesVaultColumnPredicateInstant
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_time_condition import NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition


class TestNetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition(self):
        """Test NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultQueryCriteriaTimeCondition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
