"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_identity_abstract_party import NetCordaCoreIdentityAbstractParty
from openapi_client.model.net_corda_core_node_services_vault_constraint_info import NetCordaCoreNodeServicesVaultConstraintInfo
globals()['NetCordaCoreIdentityAbstractParty'] = NetCordaCoreIdentityAbstractParty
globals()['NetCordaCoreNodeServicesVaultConstraintInfo'] = NetCordaCoreNodeServicesVaultConstraintInfo
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_linear_state_query_criteria_all_of import NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf


class TestNetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf(self):
        """Test NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultQueryCriteriaLinearStateQueryCriteriaAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
