"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.io_vertx_ext_auth_user import IoVertxExtAuthUser


class TestIoVertxExtAuthUser(unittest.TestCase):
    """IoVertxExtAuthUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoVertxExtAuthUser(self):
        """Test IoVertxExtAuthUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IoVertxExtAuthUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
