"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_query_criteria import NetCordaCoreNodeServicesVaultQueryCriteria
globals()['NetCordaCoreNodeServicesVaultQueryCriteria'] = NetCordaCoreNodeServicesVaultQueryCriteria
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_and_composition_all_of import NetCordaCoreNodeServicesVaultQueryCriteriaAndCompositionAllOf


class TestNetCordaCoreNodeServicesVaultQueryCriteriaAndCompositionAllOf(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultQueryCriteriaAndCompositionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultQueryCriteriaAndCompositionAllOf(self):
        """Test NetCordaCoreNodeServicesVaultQueryCriteriaAndCompositionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultQueryCriteriaAndCompositionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
