"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_state_ref import NetCordaCoreContractsStateRef
from openapi_client.model.net_corda_core_crypto_transaction_signature import NetCordaCoreCryptoTransactionSignature
from openapi_client.model.net_corda_core_identity_party import NetCordaCoreIdentityParty
from openapi_client.model.net_corda_core_serialization_serialized_bytes_net_corda_core_transactions_core_transaction import NetCordaCoreSerializationSerializedBytesNetCordaCoreTransactionsCoreTransaction
from openapi_client.model.net_corda_core_transactions_core_transaction import NetCordaCoreTransactionsCoreTransaction
from openapi_client.model.net_corda_core_transactions_wire_transaction import NetCordaCoreTransactionsWireTransaction
globals()['NetCordaCoreContractsStateRef'] = NetCordaCoreContractsStateRef
globals()['NetCordaCoreCryptoTransactionSignature'] = NetCordaCoreCryptoTransactionSignature
globals()['NetCordaCoreIdentityParty'] = NetCordaCoreIdentityParty
globals()['NetCordaCoreSerializationSerializedBytesNetCordaCoreTransactionsCoreTransaction'] = NetCordaCoreSerializationSerializedBytesNetCordaCoreTransactionsCoreTransaction
globals()['NetCordaCoreTransactionsCoreTransaction'] = NetCordaCoreTransactionsCoreTransaction
globals()['NetCordaCoreTransactionsWireTransaction'] = NetCordaCoreTransactionsWireTransaction
from openapi_client.model.net_corda_core_transactions_signed_transaction import NetCordaCoreTransactionsSignedTransaction


class TestNetCordaCoreTransactionsSignedTransaction(unittest.TestCase):
    """NetCordaCoreTransactionsSignedTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreTransactionsSignedTransaction(self):
        """Test NetCordaCoreTransactionsSignedTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreTransactionsSignedTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
