"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_contract_state import NetCordaCoreContractsContractState
from openapi_client.model.net_corda_core_identity_party import NetCordaCoreIdentityParty
globals()['NetCordaCoreContractsContractState'] = NetCordaCoreContractsContractState
globals()['NetCordaCoreIdentityParty'] = NetCordaCoreIdentityParty
from openapi_client.model.net_corda_core_contracts_transaction_state import NetCordaCoreContractsTransactionState


class TestNetCordaCoreContractsTransactionState(unittest.TestCase):
    """NetCordaCoreContractsTransactionState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreContractsTransactionState(self):
        """Test NetCordaCoreContractsTransactionState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreContractsTransactionState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
