"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_criteria_expression import NetCordaCoreNodeServicesVaultCriteriaExpression
from openapi_client.model.net_corda_core_node_services_vault_criteria_expression_aggregate_function_expression import NetCordaCoreNodeServicesVaultCriteriaExpressionAggregateFunctionExpression
from openapi_client.model.net_corda_core_node_services_vault_criteria_expression_binary_logical import NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogical
from openapi_client.model.net_corda_core_node_services_vault_criteria_expression_column_predicate_expression import NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression
from openapi_client.model.net_corda_core_node_services_vault_criteria_expression_net_corda_core_schemas_state_persistable_boolean import NetCordaCoreNodeServicesVaultCriteriaExpressionNetCordaCoreSchemasStatePersistableBoolean
from openapi_client.model.net_corda_core_node_services_vault_criteria_expression_not import NetCordaCoreNodeServicesVaultCriteriaExpressionNot
from openapi_client.model.net_corda_core_node_services_vault_criteria_expression_not_all_of import NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf
from openapi_client.model.net_corda_core_node_services_vault_criteria_expression_object_boolean import NetCordaCoreNodeServicesVaultCriteriaExpressionObjectBoolean
globals()['NetCordaCoreNodeServicesVaultCriteriaExpression'] = NetCordaCoreNodeServicesVaultCriteriaExpression
globals()['NetCordaCoreNodeServicesVaultCriteriaExpressionAggregateFunctionExpression'] = NetCordaCoreNodeServicesVaultCriteriaExpressionAggregateFunctionExpression
globals()['NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogical'] = NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogical
globals()['NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression'] = NetCordaCoreNodeServicesVaultCriteriaExpressionColumnPredicateExpression
globals()['NetCordaCoreNodeServicesVaultCriteriaExpressionNetCordaCoreSchemasStatePersistableBoolean'] = NetCordaCoreNodeServicesVaultCriteriaExpressionNetCordaCoreSchemasStatePersistableBoolean
globals()['NetCordaCoreNodeServicesVaultCriteriaExpressionNot'] = NetCordaCoreNodeServicesVaultCriteriaExpressionNot
globals()['NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf'] = NetCordaCoreNodeServicesVaultCriteriaExpressionNotAllOf
globals()['NetCordaCoreNodeServicesVaultCriteriaExpressionObjectBoolean'] = NetCordaCoreNodeServicesVaultCriteriaExpressionObjectBoolean
from openapi_client.model.net_corda_core_node_services_vault_criteria_expression_not import NetCordaCoreNodeServicesVaultCriteriaExpressionNot


class TestNetCordaCoreNodeServicesVaultCriteriaExpressionNot(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultCriteriaExpressionNot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultCriteriaExpressionNot(self):
        """Test NetCordaCoreNodeServicesVaultCriteriaExpressionNot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultCriteriaExpressionNot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
