"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_column_object_object import NetCordaCoreNodeServicesVaultColumnObjectObject


class TestNetCordaCoreNodeServicesVaultColumnObjectObject(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultColumnObjectObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultColumnObjectObject(self):
        """Test NetCordaCoreNodeServicesVaultColumnObjectObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultColumnObjectObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
