"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_column_predicate_instant import NetCordaCoreNodeServicesVaultColumnPredicateInstant
globals()['NetCordaCoreNodeServicesVaultColumnPredicateInstant'] = NetCordaCoreNodeServicesVaultColumnPredicateInstant
from openapi_client.model.net_corda_core_node_services_vault_attachment_query_criteria_attachments_query_criteria import NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria


class TestNetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria(self):
        """Test NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultAttachmentQueryCriteriaAttachmentsQueryCriteria()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
