"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_unique_identifier import NetCordaCoreContractsUniqueIdentifier


class TestNetCordaCoreContractsUniqueIdentifier(unittest.TestCase):
    """NetCordaCoreContractsUniqueIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreContractsUniqueIdentifier(self):
        """Test NetCordaCoreContractsUniqueIdentifier"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreContractsUniqueIdentifier()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
