"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_unique_identifier import NetCordaCoreContractsUniqueIdentifier
from openapi_client.model.net_corda_core_identity_abstract_party import NetCordaCoreIdentityAbstractParty
from openapi_client.model.net_corda_core_identity_party import NetCordaCoreIdentityParty
globals()['NetCordaCoreContractsUniqueIdentifier'] = NetCordaCoreContractsUniqueIdentifier
globals()['NetCordaCoreIdentityAbstractParty'] = NetCordaCoreIdentityAbstractParty
globals()['NetCordaCoreIdentityParty'] = NetCordaCoreIdentityParty
from openapi_client.model.states_user_state import StatesUserState


class TestStatesUserState(unittest.TestCase):
    """StatesUserState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatesUserState(self):
        """Test StatesUserState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatesUserState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
