"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_column_predicate_aggregate_function_all_of import NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf


class TestNetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf(self):
        """Test NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunctionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
