"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_identity_abstract_party import NetCordaCoreIdentityAbstractParty
globals()['NetCordaCoreIdentityAbstractParty'] = NetCordaCoreIdentityAbstractParty
from openapi_client.model.net_corda_core_contracts_contract_state import NetCordaCoreContractsContractState


class TestNetCordaCoreContractsContractState(unittest.TestCase):
    """NetCordaCoreContractsContractState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreContractsContractState(self):
        """Test NetCordaCoreContractsContractState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreContractsContractState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
