"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_contract_state import NetCordaCoreContractsContractState
from openapi_client.model.net_corda_core_contracts_transaction_state_net_corda_core_contracts_contract_state import NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState
from openapi_client.model.net_corda_core_identity_party import NetCordaCoreIdentityParty
globals()['NetCordaCoreContractsContractState'] = NetCordaCoreContractsContractState
globals()['NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState'] = NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState
globals()['NetCordaCoreIdentityParty'] = NetCordaCoreIdentityParty
from openapi_client.model.net_corda_core_transactions_base_transaction import NetCordaCoreTransactionsBaseTransaction


class TestNetCordaCoreTransactionsBaseTransaction(unittest.TestCase):
    """NetCordaCoreTransactionsBaseTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreTransactionsBaseTransaction(self):
        """Test NetCordaCoreTransactionsBaseTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreTransactionsBaseTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
