"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_state_ref import NetCordaCoreContractsStateRef
from openapi_client.model.net_corda_core_identity_abstract_party import NetCordaCoreIdentityAbstractParty
from openapi_client.model.net_corda_core_node_services_vault_constraint_info import NetCordaCoreNodeServicesVaultConstraintInfo
globals()['NetCordaCoreContractsStateRef'] = NetCordaCoreContractsStateRef
globals()['NetCordaCoreIdentityAbstractParty'] = NetCordaCoreIdentityAbstractParty
globals()['NetCordaCoreNodeServicesVaultConstraintInfo'] = NetCordaCoreNodeServicesVaultConstraintInfo
from openapi_client.model.net_corda_core_node_services_vault_state_metadata import NetCordaCoreNodeServicesVaultStateMetadata


class TestNetCordaCoreNodeServicesVaultStateMetadata(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultStateMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultStateMetadata(self):
        """Test NetCordaCoreNodeServicesVaultStateMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultStateMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
