"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_context_invocation_origin_peer import NetCordaCoreContextInvocationOriginPeer


class TestNetCordaCoreContextInvocationOriginPeer(unittest.TestCase):
    """NetCordaCoreContextInvocationOriginPeer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreContextInvocationOriginPeer(self):
        """Test NetCordaCoreContextInvocationOriginPeer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreContextInvocationOriginPeer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
