"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_crypto_partial_merkle_tree import NetCordaCoreCryptoPartialMerkleTree
from openapi_client.model.net_corda_core_crypto_signature_metadata import NetCordaCoreCryptoSignatureMetadata
globals()['NetCordaCoreCryptoPartialMerkleTree'] = NetCordaCoreCryptoPartialMerkleTree
globals()['NetCordaCoreCryptoSignatureMetadata'] = NetCordaCoreCryptoSignatureMetadata
from openapi_client.model.net_corda_core_crypto_transaction_signature import NetCordaCoreCryptoTransactionSignature


class TestNetCordaCoreCryptoTransactionSignature(unittest.TestCase):
    """NetCordaCoreCryptoTransactionSignature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreCryptoTransactionSignature(self):
        """Test NetCordaCoreCryptoTransactionSignature"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreCryptoTransactionSignature()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
