"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_criteria_expression_object_boolean import NetCordaCoreNodeServicesVaultCriteriaExpressionObjectBoolean
globals()['NetCordaCoreNodeServicesVaultCriteriaExpressionObjectBoolean'] = NetCordaCoreNodeServicesVaultCriteriaExpressionObjectBoolean
from openapi_client.model.net_corda_core_node_services_vault_criteria_expression_binary_logical_all_of import NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf


class TestNetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf(self):
        """Test NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultCriteriaExpressionBinaryLogicalAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
