"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_utilities_opaque_bytes import NetCordaCoreUtilitiesOpaqueBytes
globals()['NetCordaCoreUtilitiesOpaqueBytes'] = NetCordaCoreUtilitiesOpaqueBytes
from openapi_client.model.net_corda_core_transactions_contract_upgrade_filtered_transaction_filtered_component import NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent


class TestNetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent(unittest.TestCase):
    """NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent(self):
        """Test NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreTransactionsContractUpgradeFilteredTransactionFilteredComponent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
