"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_unique_identifier import NetCordaCoreContractsUniqueIdentifier
from openapi_client.model.net_corda_core_identity_party import NetCordaCoreIdentityParty
globals()['NetCordaCoreContractsUniqueIdentifier'] = NetCordaCoreContractsUniqueIdentifier
globals()['NetCordaCoreIdentityParty'] = NetCordaCoreIdentityParty
from openapi_client.model.generated_flows_ticket_sell_flow_ticket_sell_flow_initiator_payload import GeneratedFlowsTicketSellFlowTicketSellFlowInitiatorPayload


class TestGeneratedFlowsTicketSellFlowTicketSellFlowInitiatorPayload(unittest.TestCase):
    """GeneratedFlowsTicketSellFlowTicketSellFlowInitiatorPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneratedFlowsTicketSellFlowTicketSellFlowInitiatorPayload(self):
        """Test GeneratedFlowsTicketSellFlowTicketSellFlowInitiatorPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeneratedFlowsTicketSellFlowTicketSellFlowInitiatorPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
