"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_contract_state import NetCordaCoreContractsContractState
from openapi_client.model.net_corda_core_contracts_state_ref import NetCordaCoreContractsStateRef
from openapi_client.model.net_corda_core_contracts_transaction_state_net_corda_core_contracts_contract_state import NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState
from openapi_client.model.net_corda_core_identity_party import NetCordaCoreIdentityParty
globals()['NetCordaCoreContractsContractState'] = NetCordaCoreContractsContractState
globals()['NetCordaCoreContractsStateRef'] = NetCordaCoreContractsStateRef
globals()['NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState'] = NetCordaCoreContractsTransactionStateNetCordaCoreContractsContractState
globals()['NetCordaCoreIdentityParty'] = NetCordaCoreIdentityParty
from openapi_client.model.net_corda_core_transactions_core_transaction import NetCordaCoreTransactionsCoreTransaction


class TestNetCordaCoreTransactionsCoreTransaction(unittest.TestCase):
    """NetCordaCoreTransactionsCoreTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreTransactionsCoreTransaction(self):
        """Test NetCordaCoreTransactionsCoreTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreTransactionsCoreTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
