"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from io.generated.api.cordapps_api import CordappsApi  # noqa: E501


class TestCordappsApi(unittest.TestCase):
    """CordappsApi unit test stubs"""

    def setUp(self):
        self.api = CordappsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cordapps(self):
        """Test case for cordapps

        """
        pass

    def test_cordapps_cor_dapp_flows_flows_event_register_flow_event_register_flow_initiator(self):
        """Test case for cordapps_cor_dapp_flows_flows_event_register_flow_event_register_flow_initiator

        """
        pass

    def test_cordapps_cor_dapp_flows_flows_event_update_flow_event_update_flow_initiator(self):
        """Test case for cordapps_cor_dapp_flows_flows_event_update_flow_event_update_flow_initiator

        """
        pass

    def test_cordapps_cor_dapp_flows_flows_ticket_issue_flow_ticket_issue_flow_initiator(self):
        """Test case for cordapps_cor_dapp_flows_flows_ticket_issue_flow_ticket_issue_flow_initiator

        """
        pass

    def test_cordapps_cor_dapp_flows_flows_ticket_refund_flow_ticket_refund_flow_initiator(self):
        """Test case for cordapps_cor_dapp_flows_flows_ticket_refund_flow_ticket_refund_flow_initiator

        """
        pass

    def test_cordapps_cor_dapp_flows_flows_ticket_resell_flow_ticket_resell_flow_initiator(self):
        """Test case for cordapps_cor_dapp_flows_flows_ticket_resell_flow_ticket_resell_flow_initiator

        """
        pass

    def test_cordapps_cor_dapp_flows_flows_ticket_sell_flow_ticket_sell_flow_initiator(self):
        """Test case for cordapps_cor_dapp_flows_flows_ticket_sell_flow_ticket_sell_flow_initiator

        """
        pass

    def test_cordapps_cor_dapp_flows_flows_ticket_update_flow_ticket_update_flow_initiator(self):
        """Test case for cordapps_cor_dapp_flows_flows_ticket_update_flow_ticket_update_flow_initiator

        """
        pass

    def test_cordapps_cor_dapp_flows_flows_user_register_flow_user_register_flow_initiator(self):
        """Test case for cordapps_cor_dapp_flows_flows_user_register_flow_user_register_flow_initiator

        """
        pass

    def test_cordapps_cor_dapp_flows_flows_user_update_flow_user_update_flow_initiator(self):
        """Test case for cordapps_cor_dapp_flows_flows_user_update_flow_user_update_flow_initiator

        """
        pass

    def test_cordapps_cor_dapp_flows_flows_vendor_register_flow_vendor_register_flow_initiator(self):
        """Test case for cordapps_cor_dapp_flows_flows_vendor_register_flow_vendor_register_flow_initiator

        """
        pass

    def test_cordapps_cor_dapp_flows_flows_vendor_update_flow_vendor_update_flow_initiator(self):
        """Test case for cordapps_cor_dapp_flows_flows_vendor_update_flow_vendor_update_flow_initiator

        """
        pass

    def test_cordapps_cordapp_flows(self):
        """Test case for cordapps_cordapp_flows

        """
        pass

    def test_cordapps_progress_tracker(self):
        """Test case for cordapps_progress_tracker

        """
        pass


if __name__ == '__main__':
    unittest.main()
