"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_context_actor_id import NetCordaCoreContextActorId
from openapi_client.model.net_corda_core_context_auth_service_id import NetCordaCoreContextAuthServiceId
globals()['NetCordaCoreContextActorId'] = NetCordaCoreContextActorId
globals()['NetCordaCoreContextAuthServiceId'] = NetCordaCoreContextAuthServiceId
from openapi_client.model.net_corda_core_context_actor import NetCordaCoreContextActor


class TestNetCordaCoreContextActor(unittest.TestCase):
    """NetCordaCoreContextActor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreContextActor(self):
        """Test NetCordaCoreContextActor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreContextActor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
