"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_identity_abstract_party import NetCordaCoreIdentityAbstractParty


class TestNetCordaCoreIdentityAbstractParty(unittest.TestCase):
    """NetCordaCoreIdentityAbstractParty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreIdentityAbstractParty(self):
        """Test NetCordaCoreIdentityAbstractParty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreIdentityAbstractParty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
