"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_node_services_vault_column_predicate_aggregate_function import NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction
from openapi_client.model.net_corda_core_node_services_vault_column_predicate_between import NetCordaCoreNodeServicesVaultColumnPredicateBetween
from openapi_client.model.net_corda_core_node_services_vault_column_predicate_binary_comparison import NetCordaCoreNodeServicesVaultColumnPredicateBinaryComparison
from openapi_client.model.net_corda_core_node_services_vault_column_predicate_collection_expression import NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression
from openapi_client.model.net_corda_core_node_services_vault_column_predicate_equality_comparison import NetCordaCoreNodeServicesVaultColumnPredicateEqualityComparison
from openapi_client.model.net_corda_core_node_services_vault_column_predicate_likeness import NetCordaCoreNodeServicesVaultColumnPredicateLikeness
from openapi_client.model.net_corda_core_node_services_vault_column_predicate_null_expression import NetCordaCoreNodeServicesVaultColumnPredicateNullExpression
globals()['NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction'] = NetCordaCoreNodeServicesVaultColumnPredicateAggregateFunction
globals()['NetCordaCoreNodeServicesVaultColumnPredicateBetween'] = NetCordaCoreNodeServicesVaultColumnPredicateBetween
globals()['NetCordaCoreNodeServicesVaultColumnPredicateBinaryComparison'] = NetCordaCoreNodeServicesVaultColumnPredicateBinaryComparison
globals()['NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression'] = NetCordaCoreNodeServicesVaultColumnPredicateCollectionExpression
globals()['NetCordaCoreNodeServicesVaultColumnPredicateEqualityComparison'] = NetCordaCoreNodeServicesVaultColumnPredicateEqualityComparison
globals()['NetCordaCoreNodeServicesVaultColumnPredicateLikeness'] = NetCordaCoreNodeServicesVaultColumnPredicateLikeness
globals()['NetCordaCoreNodeServicesVaultColumnPredicateNullExpression'] = NetCordaCoreNodeServicesVaultColumnPredicateNullExpression
from openapi_client.model.net_corda_core_node_services_vault_column_predicate_instant import NetCordaCoreNodeServicesVaultColumnPredicateInstant


class TestNetCordaCoreNodeServicesVaultColumnPredicateInstant(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultColumnPredicateInstant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultColumnPredicateInstant(self):
        """Test NetCordaCoreNodeServicesVaultColumnPredicateInstant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultColumnPredicateInstant()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
