"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_context_trace_invocation_id import NetCordaCoreContextTraceInvocationId
from openapi_client.model.net_corda_core_context_trace_session_id import NetCordaCoreContextTraceSessionId
globals()['NetCordaCoreContextTraceInvocationId'] = NetCordaCoreContextTraceInvocationId
globals()['NetCordaCoreContextTraceSessionId'] = NetCordaCoreContextTraceSessionId
from openapi_client.model.net_corda_core_context_trace import NetCordaCoreContextTrace


class TestNetCordaCoreContextTrace(unittest.TestCase):
    """NetCordaCoreContextTrace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreContextTrace(self):
        """Test NetCordaCoreContextTrace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreContextTrace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
