"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_unique_identifier import NetCordaCoreContractsUniqueIdentifier
from openapi_client.model.net_corda_core_identity_abstract_party import NetCordaCoreIdentityAbstractParty
from openapi_client.model.states_ticket_state import StatesTicketState
from openapi_client.model.states_vendor_state import StatesVendorState
globals()['NetCordaCoreContractsUniqueIdentifier'] = NetCordaCoreContractsUniqueIdentifier
globals()['NetCordaCoreIdentityAbstractParty'] = NetCordaCoreIdentityAbstractParty
globals()['StatesTicketState'] = StatesTicketState
globals()['StatesVendorState'] = StatesVendorState
from openapi_client.model.states_event_state import StatesEventState


class TestStatesEventState(unittest.TestCase):
    """StatesEventState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatesEventState(self):
        """Test StatesEventState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatesEventState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
