"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_unique_identifier import NetCordaCoreContractsUniqueIdentifier
globals()['NetCordaCoreContractsUniqueIdentifier'] = NetCordaCoreContractsUniqueIdentifier
from openapi_client.model.generated_query_flows_ticket_info_by_vendor_ticket_info_by_vendor_initiator_payload import GeneratedQueryFlowsTicketInfoByVendorTicketInfoByVendorInitiatorPayload


class TestGeneratedQueryFlowsTicketInfoByVendorTicketInfoByVendorInitiatorPayload(unittest.TestCase):
    """GeneratedQueryFlowsTicketInfoByVendorTicketInfoByVendorInitiatorPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneratedQueryFlowsTicketInfoByVendorTicketInfoByVendorInitiatorPayload(self):
        """Test GeneratedQueryFlowsTicketInfoByVendorTicketInfoByVendorInitiatorPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeneratedQueryFlowsTicketInfoByVendorTicketInfoByVendorInitiatorPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
