"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_identity_abstract_party import NetCordaCoreIdentityAbstractParty
from openapi_client.model.net_corda_core_node_services_vault_constraint_info import NetCordaCoreNodeServicesVaultConstraintInfo
from openapi_client.model.net_corda_core_node_services_vault_criteria_expression_net_corda_core_schemas_state_persistable_boolean import NetCordaCoreNodeServicesVaultCriteriaExpressionNetCordaCoreSchemasStatePersistableBoolean
globals()['NetCordaCoreIdentityAbstractParty'] = NetCordaCoreIdentityAbstractParty
globals()['NetCordaCoreNodeServicesVaultConstraintInfo'] = NetCordaCoreNodeServicesVaultConstraintInfo
globals()['NetCordaCoreNodeServicesVaultCriteriaExpressionNetCordaCoreSchemasStatePersistableBoolean'] = NetCordaCoreNodeServicesVaultCriteriaExpressionNetCordaCoreSchemasStatePersistableBoolean
from openapi_client.model.net_corda_core_node_services_vault_query_criteria_vault_custom_query_criteria_all_of import NetCordaCoreNodeServicesVaultQueryCriteriaVaultCustomQueryCriteriaAllOf


class TestNetCordaCoreNodeServicesVaultQueryCriteriaVaultCustomQueryCriteriaAllOf(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultQueryCriteriaVaultCustomQueryCriteriaAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultQueryCriteriaVaultCustomQueryCriteriaAllOf(self):
        """Test NetCordaCoreNodeServicesVaultQueryCriteriaVaultCustomQueryCriteriaAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultQueryCriteriaVaultCustomQueryCriteriaAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
