"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from io.generated.api.network_api import NetworkApi  # noqa: E501


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self):
        self.api = NetworkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_network_nodes(self):
        """Test case for network_nodes

        """
        pass

    def test_network_nodes_self(self):
        """Test case for network_nodes_self

        """
        pass

    def test_network_notaries(self):
        """Test case for network_notaries

        """
        pass


if __name__ == '__main__':
    unittest.main()
