"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_cordapp_cordapp_info import NetCordaCoreCordappCordappInfo
globals()['NetCordaCoreCordappCordappInfo'] = NetCordaCoreCordappCordappInfo
from openapi_client.model.net_corda_core_node_node_diagnostic_info import NetCordaCoreNodeNodeDiagnosticInfo


class TestNetCordaCoreNodeNodeDiagnosticInfo(unittest.TestCase):
    """NetCordaCoreNodeNodeDiagnosticInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeNodeDiagnosticInfo(self):
        """Test NetCordaCoreNodeNodeDiagnosticInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeNodeDiagnosticInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
