"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_amount_transfer import NetCordaCoreContractsAmountTransfer


class TestNetCordaCoreContractsAmountTransfer(unittest.TestCase):
    """NetCordaCoreContractsAmountTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreContractsAmountTransfer(self):
        """Test NetCordaCoreContractsAmountTransfer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreContractsAmountTransfer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
