"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.invocation_error import InvocationError
globals()['InvocationError'] = InvocationError
from openapi_client.model.io_bluebank_braid_corda_server_progress_progress_notification import IoBluebankBraidCordaServerProgressProgressNotification


class TestIoBluebankBraidCordaServerProgressProgressNotification(unittest.TestCase):
    """IoBluebankBraidCordaServerProgressProgressNotification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoBluebankBraidCordaServerProgressProgressNotification(self):
        """Test IoBluebankBraidCordaServerProgressProgressNotification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IoBluebankBraidCordaServerProgressProgressNotification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
