"""

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.net_corda_core_contracts_state_and_ref_net_corda_core_contracts_contract_state import NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState
from openapi_client.model.net_corda_core_node_services_vault_state_metadata import NetCordaCoreNodeServicesVaultStateMetadata
globals()['NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState'] = NetCordaCoreContractsStateAndRefNetCordaCoreContractsContractState
globals()['NetCordaCoreNodeServicesVaultStateMetadata'] = NetCordaCoreNodeServicesVaultStateMetadata
from openapi_client.model.net_corda_core_node_services_vault_page_net_corda_core_contracts_contract_state import NetCordaCoreNodeServicesVaultPageNetCordaCoreContractsContractState


class TestNetCordaCoreNodeServicesVaultPageNetCordaCoreContractsContractState(unittest.TestCase):
    """NetCordaCoreNodeServicesVaultPageNetCordaCoreContractsContractState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCordaCoreNodeServicesVaultPageNetCordaCoreContractsContractState(self):
        """Test NetCordaCoreNodeServicesVaultPageNetCordaCoreContractsContractState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetCordaCoreNodeServicesVaultPageNetCordaCoreContractsContractState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
