# Generated by Django 3.1.6 on 2021-02-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
