# Generated by Django 3.1.6 on 2021-02-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketuser', '0002_auto_20210218_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketuser',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
